### ISSUE TITLE
[Register for Build-a-thon 2022]: 

### ISSUE THREAD

**Issue by tuha1301** [vrra/FGAN-Build-a-thon#20]
### Team name

Du

### Total number of team members

1

### Contact Details of team member 1

Fathi.abdeldayem@du.ae

### Contact Details of team member 2

Fathi.abdeldayem@du.ae

### Contact Details of team member 3

Fathi.abdeldayem@du.ae

### Contact Details of team member 4

Fathi.abdeldayem@du.ae 

### Contact Details of mentor

Fathi.abdeldayem@du.ae

### tell us more about yourself

name-1, designation-1, affiliation-1, country-1 
 name-2, designation-2, affiliation-2, country-2

### Code of Conduct

- [X] I agree to follow the Challenge Code of Conduct

**Comment by vrra** [comment]
https://extranet.itu.int/sites/itu-t/focusgroups/an/input/FGAN-I-301.zip
