### ISSUE TITLE
[Register for Build-a-thon 2022]: 

### ISSUE THREAD

**Issue by ar-alv** [vrra/FGAN-Build-a-thon#24]
### Team name

digital_twins

### Total number of team members

2

### Contact Details of team member 1

ar-alv.pendasrecondo@rakuten.com
alvaropr97@gmail.com

### Contact Details of team member 2

ar-j.fusterdelafuent@rakuten.com
jaimefusterf@gmail.com

### Contact Details of mentor

paul.harvey@glasgow.ac.uk

### tell us more about yourself

Álvaro Pendas Recondo, engineer intern at Rakuten Mobile Inc. in Tokyo.
Jaime Fúster de la Fuente, engineer intern at Rakuten Mobile Inc. in Tokyo.

### Code of Conduct

- [X] I agree to follow the Challenge Code of Conduct

**Comment by vrra** [comment]
https://extranet.itu.int/sites/itu-t/focusgroups/an/input/FGAN-I-303.docx
