### ISSUE TITLE
[Register for Build-a-thon 2022]: 

### ISSUE THREAD

**Issue by vsathishgithub** [vrra/FGAN-Build-a-thon#30]
### Team name

Heartifiial Intelligems

### Total number of team members

4

### Contact Details of team member 1

sathish.venkateswaran@nokia.com

### Contact Details of team member 2

sarvasuddi.balaganesh@nokia.com

### Contact Details of team member 3

lalit.divakarla@gmail.com

### Contact Details of team member 4

vkdevulapalli@gmail.com

### Contact Details of mentor

rajat.duggal@nokia.com

### tell us more about yourself

Sathish Venkateswaran, Technical Specialist, NOKIA Networks, India, Bengaluru
Sarvasuddi Balaganesh, SW Engineer, NOKIA Networks, India, Bengaluru
Rajat Duggal, System Specification Engineer, NOKIA Networks, India, Bengaluru
Sree Ganesh Lalitaditya Divakarla, Student, PES College, India, Bengaluru
Vaibhava Krishna Devulapali, Student, PES College, India, Bengaluru

### Code of Conduct

- [X] I agree to follow the Challenge Code of Conduct

**Comment by vrra** [comment]
https://extranet.itu.int/sites/itu-t/focusgroups/an/input/FGAN-I-297-R1.docx
