### ISSUE TITLE
[Register for Build-a-thon 2022]: 

### ISSUE THREAD

**Issue by ashokkamaraj** [vrra/FGAN-Build-a-thon#31]
### Team name

Avengers

### Total number of team members

4

### Contact Details of team member 1

ashok.kamaraj@nokia.com

### Contact Details of team member 2

srinwaynti.samaddar@nokia.com

### Contact Details of team member 3

bhuvanmaddipudi@gmail.com

### Contact Details of team member 4

swaroopsreepuram2611@gmail.com

### Contact Details of mentor

sivaramakrishnan.swaminathan@nokia.com

### tell us more about yourself

Ashok Kamaraj, Technical Specialist, NOKIA Networks, Bengaluru, India
Srinwaynti Samaddar, SW Engineer, NOKIA Networks, Bengaluru, India
Sivaramakrishnan Swaminathan, Senior Standardization Specialist, NOKIA Networks, Bengaluru, India
M SRI BHUVAN, Student, DSCE, Bengaluru, India
NAGASWAROOP S N, Student, DSCE, Bengaluru, India

### Code of Conduct

- [X] I agree to follow the Challenge Code of Conduct

**Comment by vrra** [comment]
https://extranet.itu.int/sites/itu-t/focusgroups/an/input/FGAN-I-295-R1a.docx
