### ISSUE TITLE
[Register for Build-a-thon 2022]: 

### ISSUE THREAD

**Issue by koshin43** [vrra/FGAN-Build-a-thon#32]
### Team name

morse coders

### Total number of team members

4

### Contact Details of team member 1

kodandram.ranganath@nokia.com

### Contact Details of team member 2

ayushi.khandal@nokia.com

### Contact Details of team member 3

kunalsatishm.cs20@rvce.edu.in

### Contact Details of team member 4

prikshit.cs20@rvce.edu.in

### Contact Details of mentor

rakshesh.p_bhatt@nokia.com

### tell us more about yourself

Kodandram Ranganath, Technical Specialist, NOKIA Networks, Bengaluru, India
Ayushi Khandal, SW Engineer, NOKIA Networks, Bengaluru, India
Rakshesh P Bhatt, Senior Security Standardization Specialist, NOKIA Networks, Bengaluru, India
Kunal Mahajan, Student, RVCE, Bengaluru, India
Prikshit CS, Student, RVCE, Bengaluru, India

### Code of Conduct

- [X] I agree to follow the Challenge Code of Conduct

**Comment by vrra** [comment]
https://extranet.itu.int/sites/itu-t/focusgroups/an/input/FGAN-I-299.docx
