### ISSUE TITLE
[Register for Build-a-thon 2022]: Tech Rangers

### ISSUE THREAD

**Issue by ebel-frank** [vrra/FGAN-Build-a-thon#35]
### Team name

Tech Rangers

### Total number of team members

3

### Contact Details of team member 1

frankcebeledike@gmail.com

### Contact Details of team member 2

emmanueleggah@gmail.com

### Contact Details of team member 3

oche.m1902995@st.futminna.edu.ng

### Contact Details of mentor

james.agajo@futminna.edu.ng

### tell us more about yourself

Frank C. Ebeledike - Student - FUT Minna - Nigeria
Emmanuel Othniel Eggah - Student - FUT Minna - Nigeria
Abel Oche Moses - Student - FUT Minna - Nigeria
Dr James Agajo - Associate Professor, PhD (Telecommunication and Computer Engineering), Head of Department, Computer Engineering - FUT Minna - Nigeria

### Code of Conduct

- [X] I agree to follow the Challenge Code of Conduct

**Comment by vrra** [comment]
https://extranet.itu.int/sites/itu-t/focusgroups/an/input/FGAN-I-298-R2.docx
