### ISSUE TITLE
[Register for Build-a-thon 2022]: 

### ISSUE THREAD

**Issue by justdebanka** [vrra/FGAN-Build-a-thon#56]
### Team name

AI_ML_SSD

### Total number of team members

3

### Contact Details of team member 1

subidh@iitbhilai.ac.in

### Contact Details of team member 2

sudevp@iitbhilai.ac.in

### Contact Details of team member 3

debanka.giri@cse.iitd.ac.in

### Contact Details of mentor

subidh@iitbhilai.ac.in

### tell us more about yourself

Dr. Sk Subidh Ali, Assistant Prof, IIT Bhilai, India
Sudev Kumar Padhi, PHD Student, IIT Bhilai, India
Debanka Giri, Project Scientist, IIT Delhi,India

### Code of Conduct

- [X] I agree to follow the Challenge Code of Conduct

**Comment by vrra** [comment]
https://extranet.itu.int/sites/itu-t/focusgroups/an/input/FGAN-I-296-R1.docx
