### ISSUE TITLE
[Register for Build-a-thon 2022]: 

### ISSUE THREAD

**Issue by Mukil07** [vrra/FGAN-Build-a-thon#57]
### Team name

Talk nerdy to me 

### Total number of team members

4

### Contact Details of team member 1

mukilks2502@gmail.com

### Contact Details of team member 2

kalaimegu2002@gmail.com

### Contact Details of team member 3

msivvani.nitt@gmail.com

### Contact Details of team member 4

vignesh.nitt10@gmail.com

### tell us more about yourself

name-1, designation-1, affiliation-1, country-1 
Mukilan K , Electrical and Electronics Engineering, NITT, India 
Kalaimani P N, Electronics and Communication Engineering, NITT, India  
Sivvani Muthusamy, Production Engineering, NITT, India 
Vignesh S, Electrical and Electronics Engineering, NITT, India 

### Code of Conduct

- [X] I agree to follow the Challenge Code of Conduct

**Comment by jhebus** [comment]
+1 on the team name :D
