### ISSUE TITLE
[Register for Build-a-thon 2022]: 

### ISSUE THREAD

**Issue by roboticist8** [vrra/FGAN-Build-a-thon#63]
### Team name

TCS SMART Machine

### Total number of team members

3

### Contact Details of team member 1

ck.singh1@tcs.com

### Contact Details of team member 2

ayush.k8@tcs.com

### Contact Details of team member 3

vipul.sanap1@tcs.com

### tell us more about yourself

Chandan Singh, Researcher, TCS, India
Ayush Kumar, Researcher, TCS, India
Vipul Sanap, Researcher, TCS, India 

We are part of Smart Machine group in TCS Robotics Lab.

### Code of Conduct

- [X] I agree to follow the Challenge Code of Conduct

**Comment by vrra** [comment]
https://extranet.itu.int/sites/itu-t/focusgroups/an/input/FGAN-I-300.docx
