### ISSUE TITLE
[Register for Build-a-thon 2022]: 

### ISSUE THREAD

**Issue by justdebanka** [vrra/FGAN-Build-a-thon#65]
### Team name

AI_ML_SSD

### Total number of team members

4

### Contact Details of team member 1

debanka.giri@cse.iitd.ac.in

### Contact Details of team member 2

sudevp@iitbhilai.ac.in

### Contact Details of team member 3

nitinkumar@iitbhilai.ac.in

### Contact Details of team member 4

mohitkumar@iitbhilai.ac.in

### Contact Details of mentor

subidh@iitbhilai.ac.in

### tell us more about yourself

Debanka Giri, Project Scientist, IIT Delhi
Sudev Kumar Padhi, PHD, IIT Bhilai, India
Nitin kumar Choudhary, M.Tech, IIT Bhilai, India
Mohit kumar, B.Tech, IIT Bhilai, India

### Code of Conduct

- [X] I agree to follow the Challenge Code of Conduct

**Comment by vrra** [comment]
https://extranet.itu.int/sites/itu-t/focusgroups/an/input/FGAN-I-296-R1.docx
