### ISSUE TITLE
[Register for Build-a-thon 2022]: 

### ISSUE THREAD

**Issue by muneebpandith** [vrra/FGAN-Build-a-thon#67]
### Team name

Roger That

### Total number of team members

2

### Contact Details of team member 1

musaibmn@gmail.com

### Contact Details of team member 2

suhaibajaz.11@gmail.com

### tell us more about yourself

Musaib Amin Khuroo, Diploma CSE, JKSBOTE, India
Suhaib Ajaz, BTech CSE, University of Kashmir, India

### Code of Conduct

- [X] I agree to follow the Challenge Code of Conduct

**Comment by vrra** [comment]
https://extranet.itu.int/sites/itu-t/focusgroups/an/input/FGAN-I-305.docx

**Comment by vrra** [comment]
https://extranet.itu.int/sites/itu-t/focusgroups/an/input/FGAN-I-305.docx
